const int HIVE_TYPE_ID_ACTOR_VO = 1;
const int HIVE_TYPE_ID_GENRE_VO = 2;
const int HIVE_TYPE_ID_MOVIE_VO = 3;

const String BOX_NAME_ACTOR_VO = "BOX_NAME_ACTOR_VO";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_GENRE_VO = "BOX_NAME_GENRE_VO";
